spring.application.name=AdvancedApplication


spring.datasource.url=jdbc:postgresql://localhost:1234/shop
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=sibo

server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
